In [2]:
import numpy as np
import pandas as pd

In [3]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [4]:
df = pd.concat([flats,houses],ignore_index=True)

In [5]:
df = df.sample(df.shape[0],ignore_index=True)

In [6]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 56 Gurgaon,flat,kiran residency,1.50,6648.0,2256.0,Built Up area: 2250 (209.03 sq.m.),3,5,3+,"pooja room,study room","000, Sector 56 Gurgaon, Gurgaon, Haryana",4.0,South-East,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...",Brokers please excuse\n3 bhk study room pooja ...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 86 Gurgaon,flat,dlf the skycourt,1.55,8031.0,1930.0,Super Built up area 1930(179.3 sq.m.)Built Up ...,3,3,3,not available,"Sector 86 Gurgaon, Gurgaon, Haryana",5.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...","Dlf skycourt , new gurgaon\nReady to move\nPar...","['1 Fan', '1 Wardrobe', 'No AC', 'No Bed', 'No...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 95 Gurgaon,flat,ramsons kshitij,0.33,3911.0,844.0,Super Built up area 767(71.26 sq.m.),2,2,1,others,"Sector 95 Gurgaon, Gurgaon, Haryana",14.0,South,0 to 1 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...",Corner flat with private balcony. The property...,"['2 Bed', '1 Wardrobe', '3 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 56 Gurgaon,flat,the castle society,2.00,8695.0,2300.0,Super Built up area 2300(213.68 sq.m.),4,4,2,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",4.0,NaN,By 2023,"['Sector 54 chowk metro station', 'Sector metr...",We are the proud owners of this 4 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,2 BHK Flat in Sohna,flat,signature global park,0.54,7248.0,745.0,Carpet area: 745 (69.21 sq.m.),2,1,3,not available,"J-26, Sohna, Gurgaon, Haryana",1.0,NaN,Within 6 months,"['Sector 55-56 metro', 'Global city centre', '...",Park facing property for the unique view,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Connectivity5 out of 5', 'Management4 out of..."

In [7]:
df.to_csv('gurgaon_properties.csv',index=False)